### ISSUE TITLE
Rename `currency` contract

### ISSUE THREAD

**Issue by duelingbenjos** [XianChain/xian#14]
We should rename the `currency` contract to something else. Because if we at some point want to interact with another network like Lamden, it might be an issue if their TAU and our XIAN are both the same contract.

Either we name it `xian` if we are sure about the name or we call it something more abstract.

**Comment by duelingbenjos** [comment]
Not sure I see the problem, can you explain a bit more ? We should be able to handle conflicting contract names from different networks.

**Comment by crosschainer** [comment]
Keep as is in the file structure. Just rename to xian in the abci_genesis

**Comment by Endogen** [comment]
> Not sure I see the problem, can you explain a bit more ? We should be able to handle conflicting contract names from different networks.

In another network the main token is a different asset than XIAN on the Xian network but if we keep the naming then both run under the same contract name. I can imagine that we at some point want to allow importing or referencing contracts from other contracting based chains or something like that and then they need to be different or we run into issues.

> Keep as is in the file structure. Just rename to xian in the abci_genesis
Not sure if that's good. It's confusing. I know we can get away with just renaming it in genesis but i think we should do it properly. You don't want to rename the file because it's more work or do you see real issues with renaming the file?

**Comment by Endogen** [comment]
OK that makes total sense
